export const BOOKS_FETCH = {
  REQUEST: 'FETCH_BOOKS_REQUEST',
  SUCCESS: 'FETCH_BOOKS_SUCCESS',
  FAILURE: 'FETCH_BOOKS_FAILURE',
};

export const BOOKS_ACTIONS = {
  ADDED_TO_CART: 'BOOK_ADDED_TO_CART',
  REMOVED_FROM_CART: 'BOOK_REMOVED_FROM_CART',
  ALL_REMOVED_FROM_CART: 'ALL_BOOK_REMOVED_FROM_CART',
};
